# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1384f4a81ba6ee0ebc0568b8d1df5d13e53be20d980dcd717d35a6f29fe3ecd6a75e0e85536ef910bc6e6ab922dc4514b9dd0e9922f267a88d794341241cd5e4

test:
  secret_key_base: 71b720e286c6167fbd592aa1ac3f9500f8bd90718e80cc0b12fd2f9806fe089088c5ff18e7f8e7ca565530251299fae2957fe5d6404ba08fd1004918341d3c1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
